# Change these first
owner: kpAjun # Your GitHub organization or username, where this repository lives
repo: hyena-upptime # The name of this repository

sites:
  - name: Skin Station
    url: https://account.teamhyena.org
  - name: Reverse Proxy (Toronto)
    check: "tcp-ping"
    url: mc.teamhyena.org
    port: 25577
  - name: Reverse Proxy (Hefei)
  check: "tcp-ping"
  url: 120.78.128.225
  port: 7007
  - name: Main Server (Survival)
  check: "tcp-ping"
  url: minecraft.teamhyena.org
  port: 25560
  - name: Main Server (Mod)
  check: "tcp-ping"
  url: minecraft.teamhyena.org
  port: 7001
  - name: Main Server (Skyblock)
  check: "tcp-ping"
  url: minecraft.teamhyena.org
  port: 25561

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /hyena-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: HyenaMC Status Page
  introTitle: "**HyenaMC Status Page**"
  introMessage: This page collects and displays the status of key HyenaMC servers and websites, powered by Upptime and GitHub Acions.
  navbar:
    - title: Status
      href: /
    - title: GitHub Repo
      href: https://github.com/$OWNER/$REPO
    - title: HyenaMC Skin Station
      href: https://account.teamhyena.org

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
